#!/usr/bin/env bash
# Fable Method — PostToolUse convergence guard (stoploss-lite)
# Counts edits per file in the current session. Warns at 5 edits on the same
# file, escalates at 8. Defers entirely to a real `stoploss` tool if one is on PATH.

# Defer to the user's real stoploss tool if installed
if command -v stoploss >/dev/null 2>&1; then
  exit 0
fi

INPUT=$(cat)

STATE_DIR="${CLAUDE_PROJECT_DIR:-.}/.fable-session"
mkdir -p "${STATE_DIR}" 2>/dev/null || exit 0
STATS="${STATE_DIR}/edit-stats.txt"
touch "${STATS}"

# Extract edited file path from tool input JSON (Edit/Write/MultiEdit)
FILE=$(printf '%s' "$INPUT" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    ti = d.get('tool_input', {}) or {}
    print(ti.get('file_path', ''))
except Exception:
    print('')
" 2>/dev/null)

[ -z "$FILE" ] && exit 0

echo "$FILE" >> "${STATS}"
COUNT=$(grep -cxF "$FILE" "${STATS}" 2>/dev/null || echo 0)

if [ "$COUNT" -ge 8 ]; then
  cat <<EOF
{
  "decision": "block",
  "reason": "CONVERGENCE GUARD (fable-method): '$FILE' has been edited ${COUNT} times this session. This is a fix-loop signal. STOP editing. Apply the convergence-guard skill: freeze edits, summarize the failed attempts and their common cause, state the hypothesis being bet on, and propose 2 alternative strategies to the user. Do not edit this file again without user approval."
}
EOF
  exit 0
fi

if [ "$COUNT" -eq 5 ]; then
  cat <<EOF
{
  "decision": "block",
  "reason": "CONVERGENCE GUARD (fable-method): '$FILE' has now been edited 5 times this session. Warning threshold reached. Before the next edit to this file, explicitly state to the user whether the approach is converging (tests trending green) or looping. If looping, switch strategy now rather than at edit 8."
}
EOF
  exit 0
fi

exit 0
